from tkinter import*

cal = Tk()
cal.geometry("300x400")
am_ent = Text(cal,width=27,height=3)
am_ent.grid(row=0 , column=0, columnspan=5)

num_7_btn = Button(cal,text=7, width=5, height=3,)
num_7_btn.grid(row=3, column=1)
num_8_btn = Button(cal,text=8, width=5, height=3)
num_8_btn.grid(row=3, column=2)
num_9_btn = Button(cal,text=9,  width=5, height=3)
num_9_btn.grid(row=3, column=3)
num_4_btn = Button(cal,text=4, width=5, height=3)
num_4_btn.grid(row=4, column=1)
num_5_btn = Button(cal,text=5, width=5, height=3)
num_5_btn.grid(row=4, column=2)
num_6_btn = Button(cal,text=6, width=5, height=3)
num_6_btn.grid(row=4, column=3)
num_1_btn = Button(cal,text=1, width=5, height=3)
num_1_btn.grid(row=5, column=1)
num_2_btn = Button(cal,text=2, width=5, height=3)
num_2_btn.grid(row=5, column=2)
num_3_btn = Button(cal,text=3, width=5, height=3)
num_3_btn.grid(row=5, column=3)
num_0_btn = Button(cal,text=0, width=12,height=3)
num_0_btn.grid(row=6,column=1, columnspan=2)

div_btn= Button(cal, text="/", width=12, height=2)
div_btn.grid(row=2, column=1, columnspan=2)
mul_btn= Button(cal, text="*", width=12, height=2)
mul_btn.grid(row=2, column=3, columnspan=2)
mi_btn = Button(cal , text= "-", width=5, height=3)
mi_btn.grid(row=3, column=4)
pl_btn = Button(cal , text= "+", width=5, height=3)
pl_btn.grid(row=4, column=4)
com_btn = Button(cal, text= ".", width=5, height=3)
com_btn.grid(row=6, column=3)
ent_btn = Button(cal, text= "=", width=5, height=7)
ent_btn.grid(row=5, column=4 ,rowspan=2)

cal.mainloop()